name: spec2vec-dev
channels:
  - bioconda
  - conda-forge
  - defaults
  - nlesc
dependencies:
  - gensim >=3.8.0
  - matchms >=0.6.0
  - numba >=0.47
  - numpy
  - pip
  - python >=3.7,<3.9
  - pip:
    - -e ..[dev]
