name: spec2vec-dev
channels:
  - bioconda
  - conda-forge
  - defaults
  - nlesc
dependencies:
  - gensim >=3.8.0
  - matchms >=0.6.2
  - numba >=0.51
  - numpy
  - pip
  - python >=3.7
  - tqdm
  - pip:
    - -e ..[dev]
