name: spec2vec-readthedocs
channels:
  - bioconda
  - conda-forge
  - nlesc
  - defaults
dependencies:
  - gensim >=3.8.0
  - matchms
  - numpy
  - pip
  - python >=3.7,<3.8
  - scipy
  - pip:
    - recommonmark
    - ruamel.yaml
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-apidoc

